pull_request_rules:
  - name: Automatic merge on CI success and all reviews are approved
    conditions:
      - status-success=continuous-integration/codeship
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
      - base=master
      - label=ready-to-merge
    actions:
      merge:
        method: squash
        strict: smart
